### ISSUE TITLE
Type errors in functions defined in `annotations.py`

### ISSUE THREAD

**Issue by soucelover** [artemkaFismat/snb#2]
### Issue
According to type annotations, parameter `mean` of function `addNoise` must have type `int` but you specify it by parameter with default value of type `float`. Also variables you specify have names that have other parameters of this function. That means that these positional parameters are placed on wrong places.

Error applies to `addNoise_salt_pepper` and `addNoise_posson` functions.

Such behaviour was found on Python 3.12 with Pylance linter in VS Code.

### Proposal
It's proposed to pass these parameters as keyword arguments like `noise_amount=noise_amount`. Otherwise these parameters are likely to be place on wrong places.

**Comment by artemkaFismat** [comment]
The errors have been fixed.
